"""opciones en conversaciones

Revision ID: 1f3825bdc3ed
Revises: cad562383689
Create Date: 2026-06-18 06:46:08.249588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f3825bdc3ed'
down_revision: Union[str, None] = 'cad562383689'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversaciones', sa.Column('opciones', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversaciones', 'opciones')
    # ### end Alembic commands ###
