"""celular en empresas

Revision ID: 4d3689a85789
Revises: 1f3825bdc3ed
Create Date: 2026-06-18 06:57:15.435361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d3689a85789'
down_revision: Union[str, None] = '1f3825bdc3ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('celular', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresas', 'celular')
    # ### end Alembic commands ###
