"""tablas iniciales

Revision ID: cad562383689
Revises: 
Create Date: 2026-06-17 18:03:55.508118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cad562383689'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversaciones_telefono'), 'conversaciones', ['telefono'], unique=False)
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('alias', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('escalamientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('empresa_nombre', sa.String(length=150), nullable=True),
    sa.Column('motivo', sa.String(length=50), nullable=True),
    sa.Column('texto_original', sa.Text(), nullable=True),
    sa.Column('atendido', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faqs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tema', sa.String(length=50), nullable=False),
    sa.Column('pregunta_corta', sa.String(length=150), nullable=True),
    sa.Column('respuesta', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('faqs')
    op.drop_table('escalamientos')
    op.drop_table('empresas')
    op.drop_index(op.f('ix_conversaciones_telefono'), table_name='conversaciones')
    op.drop_table('conversaciones')
    # ### end Alembic commands ###
